- README.md
- src/main/java/com/deque/axe/AXE.java
- src/test/java/com/deque/axe/ExampleTest.java
Here's the proposed PR. Please let me know if you have any concerns and if anything needs to be changed. I've overloaded both `AXE.inject` and the `Builder` constructor methods to skip iframe checks. This doesn't create a breaking change. Once merged, someone from Deque would have to bump it and publish it.
Thanks!
> Resolves dequelabs/axe-selenium-java#10 Allow option to skip iframe injection

- src/main/java/com/deque/axe/AXE.java
- src/test/java/com/deque/axe/ExampleTest.java
- src/test/resources/axe-error.js
This patch prevents `axe-selenium-java` from swallowing errors returned from `axe-core.run()`. Previously, if axe-core errored during an analysis, the error would not be reported back to the user, but instead, would be swallowed. This would _probably_ cause undefined behavior in people's accessibility tests.
Now, if an error is raised in axe-core, it will be "re-thrown" as an `AXE.AxeRuntimeError`. This allows the caller to handle the error however they see fit. Note that `AXE.AxeRuntimeError` extends `RuntimeException` and does **not require** users to `try/catch` the `analyze()` call which may cause it to be thrown.
Closes #26.
> BREAKING CHANGE: throw errors returned by axe-core's `run` method

- src/main/java/com/deque/axe/AXE.java
- src/test/java/com/deque/axe/ExampleTest.java
- src/test/resources/timeout.js
This patch adds a `Builder#setTimeout` method for setting a configurable script timeout. Prior to this, we'd always timeout after 30 seconds.
Closes #17.
> feat: add configurable script timeout

- .gitignore
- CHANGELOG.md
This patch adds a `CHANGLOG.md` file, which includes the 3.0.0 release.
Normally this would be done in a release branch, but #24 is already open, so 🤷‍♀️ 
> docs: add `CHANGELOG.md`

- README.md
This patch adds a "deployment" section to the README. This should help out other maintainers rather than leaving them in the dark.
Also, my editor formatted the README :)
> docs(README): Add deployment section

- pom.xml
It looks like Java 12 the minimum allowed version is now Java 7, so updating the target to ensure compatibility with the latest.
Closes issue:
> fix: set minimum compiler source/target to java 7

- src/main/java/com/deque/axe/AXE.java
- src/test/java/com/deque/axe/ExampleTest.java
- src/test/resources/test-app.js
According to the documentation, include and exclude should not be passed in options. 
They should be passed as context.
Also added tests to catch this error.
Closes issue: #42
> Fix work witn few include and exclude options

- .circleci/config.yml
The github release script failed because we didn't have our env variables set up. This should fix it.
https://app.circleci.com/pipelines/github/dequelabs/axe-core-maven-html/197/workflows/d092cacf-e54b-471f-8129-8d4ef8ef8716/jobs/391
> ci: add context when releasing

- src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
In webdriverjs we default to setting this to "off", so we should do so here as well (see https://github.com/dequelabs/axe-core-npm/blob/develop/packages/webdriverjs/lib/axe-injector.js#L12-L15)
> fix: turn sandbox buster off by default

- src/main/java/com/deque/html/axecore/results/AxeRuntimeException.java
- src/main/java/com/deque/html/axecore/results/Results.java
- src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
Changes the `errorMessage` type in the `Results` object from `String` to `AxeRuntimeException` so that full stack trace is preserved. When converted to JSON it still has the same shape. However, the `errorMessage` property of the JSON will now contain the full stack trace rather than just a one-line description. When there is no error the JSON is unchanged.
Captures all selenium errors thrown when running axe-core as well.
> feat: add full context to axe errors

- src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
- src/test/java/com/deque/html/axecore/selenium/AxeExampleUnitTest.java
- src/test/resources/html/frames/bar.html
- src/test/resources/html/frames/baz.html
- src/test/resources/html/frames/foo.html
- src/test/resources/html/iframes/bar.html
- src/test/resources/html/iframes/baz.html
- src/test/resources/html/iframes/foo.html
- src/test/resources/html/nested-frames.html
- src/test/resources/html/nested-iframes.html
Fixed to recursively find `<frame>`  and inject a script into them, not only `<iframe>`.
`<frame>` is deprecated in HTML5, but sometimes use in bad examples when teach modern & accessible coding.
ex) https://barrierfree.nict.go.jp/accessibility/whatsacs/sample/level0/index.html
Thanks!
> fix: Recursively find <frame>

- src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
- src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
Didn't like how the axe-core 4.2.0 PR handled enabling iframe communication, so I cleaned it up.
> chore: clean up iframe origin code

- src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
We can use `driver.switchTo().parentFrame()` for better recursion rather than tracking parents explicitly and having to switch to `defaultContext()` multiple times.
Running default analysis on a page with 3 i-frames including 1 nested i-frame (e.g., http://watir.com/examples/nested_iframes.html) takes [47 commands](https://app.saucelabs.com/tests/07d35a9b701a4ada87dfcb27f832f7f7) currently, this code drops it to [34 commands](https://app.saucelabs.com/tests/1e9e2438794540deb5870b57d59a9744).
Note, I was able to drop this further to [23 commands](https://app.saucelabs.com/tests/e18435a5223c443981a92531de8c46fe) by implementing script injection from an Array, but this code is a little hacky, and I'd want to discuss it more before making a real PR from it: …
> perf: Optimize iframe recursion

- .circleci/snapshot.py
- utilities/pom.xml
- utilities/src/main/java/com/deque/html/axecore/args/AxeRuleOptions.java
- utilities/src/main/java/com/deque/html/axecore/args/AxeRules.java
- utilities/src/main/java/com/deque/html/axecore/args/AxeRunContext.java
- utilities/src/main/java/com/deque/html/axecore/args/AxeRunOnlyOptions.java
- utilities/src/main/java/com/deque/html/axecore/args/AxeRunOptions.java
- utilities/src/main/java/com/deque/html/axecore/results/AxeResults.java
- utilities/src/main/java/com/deque/html/axecore/results/AxeRuntimeException.java
- utilities/src/main/java/com/deque/html/axecore/results/Check.java
- utilities/src/main/java/com/deque/html/axecore/results/CheckedNode.java
- utilities/src/main/java/com/deque/html/axecore/results/FrameContext.java
- utilities/src/main/java/com/deque/html/axecore/results/Node.java
- utilities/src/main/java/com/deque/html/axecore/results/Platform.java
- utilities/src/main/java/com/deque/html/axecore/results/Results.java
- utilities/src/main/java/com/deque/html/axecore/results/Rule.java
- utilities/src/main/java/com/deque/html/axecore/results/TestEngine.java
- utilities/src/main/java/com/deque/html/axecore/results/TestEnvironment.java
- utilities/src/main/java/com/deque/html/axecore/results/TestResults.java
- utilities/src/main/java/com/deque/html/axecore/results/TestRunner.java
- utilities/src/main/java/com/deque/html/axecore/results/TestSubject.java
- utilities/src/main/java/com/deque/html/axecore/results/ToolOptions.java
Moves all of the commonly used JSON mapping classes in Selenium and Playwright into its own package `utilities`. 
We will then import this package as dependency for each current (and new) integration(s) to save creating again for each. 
Part of issue: https://github.com/dequelabs/axe-core-maven-html/issues/207
> feat: new submodule: `utilities` to contain all the commonly used JSON mapped Java classes

- playwright/pom.xml
- pom.xml
- utilities/pom.xml
We had to manually release via CI due to `playwright` and `utilities` missing the required plugins for GPG signing and generating sources for publishing:
```sh
[ERROR] Nexus Staging Rules Failure Report
[ERROR] ==================================
[ERROR] 
[ERROR]   Rule "pom-staging" failures
[ERROR]     * Invalid POM: /com/deque/html/axe-core/virtual-superpackage/4.4.1/virtual-superpackage-4.4.1.pom: Project name missing, Project description missing
[ERROR]   Rule "signature-staging" failures
[ERROR]     * Missing Signature: '/com/deque/html/axe-core/virtual-superpackage/4.4.1/virtual-superpackage-4.4.1.pom.asc' does not exist for 'virtual-superpackage-4.4.1.pom'.
[ERROR]     * Missing Signature: '/com/deque/html/axe-core/playwright/4.4.1/playwright-4.4.1.jar.asc' does not exist for …
```
> fix: add missing plugins to superpackage, playwright and utilities required for publishing

- playwright/src/test/java/PlaywrightJavaTest.java
- selenium/src/main/java/com/deque/html/axecore/results/Check.java
- selenium/src/main/java/com/deque/html/axecore/results/CheckedNode.java
- selenium/src/main/java/com/deque/html/axecore/results/Node.java
- selenium/src/test/java/com/deque/html/axecore/selenium/AxeExampleUnitTest.java
- utilities/src/main/java/com/deque/html/axecore/results/Check.java
- utilities/src/main/java/com/deque/html/axecore/results/CheckedNode.java
- utilities/src/main/java/com/deque/html/axecore/results/Node.java
Issue: Currently, the `toString` methods for `Check`s, `CheckedNode`s, and `Node`s in Selenium and Playwright don't provide a lot of information to the user during accessibility testing. This PR overrides the `toString` methods in these instances, similar to how it's done in [Rule.java](https://github.com/dequelabs/axe-core-maven-html/blob/5fe065d85e01a0c6b0f0a252554941cd01c62f42/selenium/src/main/java/com/deque/html/axecore/results/Rule.java#L92), to provide more actionable output to the user.
> fix: improve result toString implementation to be more actionable

- .circleci/config.yml
- playwright/pom.xml
This PR fixes two things, one we want to `clean install` at the top level (not required, but in case there are any cached changes, we clean install to grab any new changes). Second, the dependency for `utilities` default scope for each dependency defaults to `compile` but this may not be the case within CI, so this fixes the scoping to compile before the tests are ran
> tests: fix Playwright tests

- scripts/pre-commit-hook.sh
This PR ensures the pre-commit hook is able to run in the `create-release` workflow: 
Tested: https://github.com/dequelabs/axe-core-maven-html/actions/runs/3406974918/jobs/5666150831 
Useful resource: https://stackoverflow.com/a/12469057 
Closes Issue: https://github.com/dequelabs/axe-core-maven-html/issues/265
> ci: ensure pre-commit hook works in release script

- .circleci/config.yml
- playwright/package-lock.json
- selenium/package-lock.json
This PR fixes an issue with out-of-sync package locks (see: https://app.circleci.com/pipelines/github/dequelabs/axe-core-maven-html/719/workflows/71b2ed2d-211a-40d6-b9c4-e14f8149b8b7/jobs/1809). 
Updated cache version to generate a new cache from new node_modules
> ci: update cache version due to missing dependencies

- .circleci/config.yml
Remove maven dependency caching because it is causing it to pull the previous version: https://app.circleci.com/pipelines/github/dequelabs/axe-core-maven-html/728/workflows/774bb7f7-9da9-493b-b5fa-64fd01fffa2e/jobs/1837?invite=true#step-108-44.
> ci: separate dependencies job into npm and do not cache maven

- .circleci/config.yml
- playwright/src/main/java/com/deque/html/axecore/playwright/AxeBuilder.java
- selenium/src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
This PR fixes the snapshot build within CI when attempting to publish snapshot as the javadoc syntax was incorrect 
See for reference: https://app.circleci.com/pipelines/github/dequelabs/axe-core-maven-html/740/workflows/4fc61439-a0ec-4044-8091-3a6551a2e31e/jobs/1878?invite=true#step-108-1000 
<details>
<summary>Rendered Docs</summary>
</details>
> ci: ensure java-doc creation runs in snapshot release

- selenium/README.md
This PR revamps our Selenium documentation to be inline with our [Playwright docs](https://github.com/dequelabs/axe-core-maven-html/tree/develop/playwright#axe-core-maven-html-playwright).
Closes: https://github.com/dequelabs/axe-core-maven-html/issues/284
> docs(selenium): revamp documentation

- playwright/package-lock.json
- playwright/src/main/java/com/deque/html/axecore/playwright/AxeBuilder.java
- playwright/src/test/java/PlaywrightJavaTest.java
- selenium/package-lock.json
- selenium/src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
- selenium/src/test/java/com/deque/html/axecore/selenium/Axe43xIntegrationTest.java
Issue: https://github.com/dequelabs/axe-devtools-npm/issues/1653
> fix: work with extremely large results

- playwright/README.md
- selenium/README.md
Remove confusing usage for `include` and `exclude` selectors when trying to include/exclude multiple elements
For reference: https://axecommunity.slack.com/archives/C01BSF8J6LS/p1679441799898339 - good catch!
> docs: remove confusing usage example for `include` and `exlcude`

- .circleci/config.yml
- .circleci/snapshot.py
This PR ensures our snapshot job runs to create a snapshot artifact once PRs are merged into develop
ref: https://app.circleci.com/pipelines/github/dequelabs/axe-core-maven-html/778/workflows/28e007ce-e856-4032-80da-5e357357c49e/jobs/2056
> ci: ensure `snapshot_release` job publishes canary artifacts

- .github/workflows/auto-patch-release.yml
Test PR: https://github.com/dequelabs/axe-core-maven-html/pull/341
Test Issue: https://github.com/dequelabs/axe-core-maven-html/issues/340
Conditional checks were tested in a personal repo: https://github.com/AdnoC/action-test/actions/workflows/push-and-dispatch.yml
Issue: https://github.com/dequelabs/axe-api-team/issues/342
> ci: enable manual run of patch release

- playwright/package-lock.json
- playwright/package.json
- selenium/package-lock.json
- selenium/package.json
> fix(playwright,selenium): pin axe-core version to accept patch updates only

- package-lock.json
- package.json
We don't use JFrog here, removing it. 
Ref: https://app.circleci.com/pipelines/github/dequelabs/axe-core-maven-html/966/workflows/b03adc1c-0e40-4a1b-9520-c73612dc88f0/jobs/2426?invite=true#step-103-0_15
> chore: remove unused dependency

- README.md
This is always broke. Removing it.
No QA Required.
> docs: remove broken CircleCI badge

- .github/workflows/create-release-candidate.yml
- .github/workflows/semantic-pr-footer.yml
- .github/workflows/semantic-pr-title.yml
- .github/workflows/sync-master-develop.yml
- .github/workflows/tests.yml
- .github/workflows/update-axe-core.yml
Closes: https://github.com/dequelabs/axe-core-maven-html/issues/402
> ci: add timeouts to all GHA workflows

- .github/workflows/tests.yml
I've been wanting to do this for a while, picked JDK 8, 11 and 17 based on the latest data from the [JetBrains EcoSystem 2023](https://www.jetbrains.com/lp/devecosystem-2023/java/) (thanks for sharing @dbjorge!). Why are we doing this? 
1. Ensure we do not use functions that's only available in later versions of Java as the minimum support we cover is Java 8
2. Ensure that we can still run our API's on later Java versions
No QA required
> test: setup JDK matrix to test multiple popular versions

- CHANGELOG.md
- package-lock.json
- package.json
- playwright/package-lock.json
- playwright/package.json
- playwright/pom.xml
- pom.xml
- selenium/package-lock.json
- selenium/package.json
- selenium/pom.xml
- utilities/pom.xml
> Release v4.9.0

- playwright/package-lock.json
- playwright/src/test/java/PlaywrightJavaTest.java
- selenium/package-lock.json
Fixes the broken lazy load iframe tests.
Ref: https://github.com/dequelabs/axe-core-npm/pull/1052
No QA needed.
> chore: update test-fixtures to fix lazy load

- .github/workflows/sync-master-develop.yml
This updates the action to fix the no pr template issue as well as switch to pr team reviewer instead of specific users 
no qa required
> ci: update sync to master to include team-reviewers

- playwright/README.md
- selenium/README.md
As per our policy to add a message about how we don't strictly follow semver to our documentation.
No QA required.
> chore: add note about semver to READMEs
