dequelabs/axe-core-maven-html

.circleci/config.yml
.gitignore
pom.xml

Before we can let anything else happen to this repository, we need CI running on every PR. This patch does exactly that.
Additionally, this patch:
- adds compiler source/target to fix build
- removes mixed tabs/spaces in `pom.xml`

ci: setup CircleCI

---

README.md

Hat tip to @mohanraj-r 
Closes https://github.com/dequelabs/axe-selenium-java/pull/36
Closes https://github.com/dequelabs/axe-selenium-java/issues/35

docs: fix README version number

---

README.md
src/main/java/com/deque/axe/AXE.java
src/test/java/com/deque/axe/ExampleTest.java
src/test/resources/test-app.js

This change allows to check multiple WebElements at once. This feature allows to check only for include elements.
Closes issue:  #40

feat: add ability to use list of WebElements 

---

.circleci/config.yml
.circleci/publish.sh

<< Describe the changes >>
Closes issue:

ci: add publish job

---

.github/PULL_REQUEST_TEMPLATE.md

chore: Remove unnecessary stuff from PR template

---

.circleci/config.yml
.circleci/snapshot.py

Closes issue: https://github.com/dequelabs/axe-core-maven-html/issues/67

ci: publish snapshot releases

---

.github/workflows/sync-master-develop.yml

ci: Add "sync branches" workflow

---

src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
src/test/java/com/deque/html/axecore/selenium/AxeBuilderUnitTest.java

https://github.com/dequelabs/axe-core-maven-html/issues/84

feat: ability to remove sandbox from iframes

---

README.md

docs: update readme for rebranding

---

package.json
src/test/java/com/deque/html/axecore/selenium/AxeBuilderUnitTest.java

chore: use exact axe-core version

---

pom.xml

https://github.com/dequelabs/axe-devtools-maven-html/issues/233

chore: override okhttp version to 3.12.12

---

package-lock.json
package.json
pom.xml
src/test/java/com/deque/html/axecore/selenium/AxeBuilderUnitTest.java

chore: use `BanVulnerableDependencies`  plugin and update to axe-core v4.1.0

---

package-lock.json
package.json

feat: bump axe-core to v4.1.1

---

src/test/java/com/deque/html/axecore/selenium/AxeExampleUnitTest.java

chore: fix include usage in test

---

.circleci/config.yml
.dependabot/config.yml
CHANGELOG.md
package-lock.json
package.json
pom.xml
src/test/java/com/deque/html/axecore/selenium/AxeBuilderUnitTest.java
src/test/java/com/deque/html/axecore/selenium/AxeExampleUnitTest.java

chore: release v4.1.0

---

.circleci/config.yml
.circleci/publish.sh
pom.xml
src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
src/main/java/com/deque/html/axecore/providers/StringAxeScriptProvider.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
src/test/java/com/deque/html/axecore/selenium/AxeIntegrationUnitTest.java

Went in CI, generated a gpg key, distributed the public key to keyservers maven central checks, and stored the exported private key in a base64 encoded string.
Then got publishing working.
Test job that succeeded: https://app.circleci.com/pipelines/github/dequelabs/axe-core-maven-html/270/workflows/8609a528-11ad-4d9d-8cf9-87b84c7c78be/jobs/575
Published artifact: https://search.maven.org/artifact/com.deque.html.axe-core/selenium/1.0.6/jar

ci: automate publishing

---

pom.xml

chore: override junit version for security

---

.circleci/config.yml
.circleci/publish.sh
CHANGELOG.md
package-lock.json
package.json
pom.xml
src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
src/main/java/com/deque/html/axecore/providers/StringAxeScriptProvider.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
src/test/java/com/deque/html/axecore/selenium/AxeIntegrationUnitTest.java

chore: release v4.1.1

---

.gitignore
src/main/java/com/deque/html/axecore/selenium/AxeReporter.java
src/test/java/com/deque/html/axecore/selenium/AxeReporterTest.java

Issue: https://github.com/dequelabs/axe-core-maven-html/issues/111

fix: reporter prints element nodes

---

pom.xml

chore: update URL for maven

---

package-lock.json
package.json

feat: bump axe-core to v4.1.2

---

src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java

feat: add ability to disable iframe injection and checking

---

.gitignore
CHANGELOG.md
package-lock.json
package.json
pom.xml
src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
src/main/java/com/deque/html/axecore/results/AxeRuntimeException.java
src/main/java/com/deque/html/axecore/results/Results.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
src/main/java/com/deque/html/axecore/selenium/AxeReporter.java
src/test/java/com/deque/html/axecore/selenium/AxeReporterTest.java

chore: release v4.1.2

---

pom.xml
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java

ci: release as java 7

---

.github/workflows/sync-master-develop.yml

ci: fix sync develop/master workflow

---

src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java

fix: ignore iframe errors for non-loaded frames

---

.npmrc
package-lock.json

chore: use public npm registry

---

src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java

Proposal: https://github.com/dequelabs/axe-api-team-proposals/blob/master/axe-integration-handle-injection-errors.md

fix: do not error on iframe injection error

---

.circleci/config.yml

ci: import gpg key for snapshot release

---

.github/workflows/auto-assign-issues.yml

ci: add github action to auto assign issues

---

package-lock.json
package.json

feat: update to use `axe-core@4.2.2`

---

package-lock.json
package.json

feat: update to use `axe-core@4.2.3`

---

CHANGELOG.md
package-lock.json
package.json
pom.xml

chore: release v4.2.2

---

.circleci/config.yml
package-lock.json
package.json
pom.xml
src/main/java/com/deque/html/axecore/axeargs/AxeRunContext.java
src/main/java/com/deque/html/axecore/extensions/WebDriverExtensions.java
src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
src/main/java/com/deque/html/axecore/providers/EmbeddedResourceAxeProvider.java
src/main/java/com/deque/html/axecore/providers/IAxeScriptProvider.java
src/main/java/com/deque/html/axecore/results/FrameContext.java
src/main/java/com/deque/html/axecore/results/Results.java
src/main/java/com/deque/html/axecore/results/TestEngine.java
src/main/java/com/deque/html/axecore/results/ToolOptions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
src/test/java/com/deque/html/axecore/selenium/Axe43xIntegrationTest.java
src/test/java/com/deque/html/axecore/selenium/AxeExampleUnitTest.java
src/test/java/com/deque/html/axecore/selenium/AxeIntegrationUnitTest.java
src/test/java/com/deque/html/axecore/selenium/AxeRunContextUnitTest.java
src/test/resources/timeout.js

Issue: https://github.com/dequelabs/axe-core-maven-html/issues/172

chore: update axe-core to v4.3.3

---

package-lock.json
src/main/java/com/deque/html/axecore/results/ToolOptions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
src/test/java/com/deque/html/axecore/selenium/Axe43xIntegrationTest.java

feat: add legacy mode option

---

error-handling.md
src/main/java/com/deque/html/axecore/extensions/WebDriverExtensions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
src/test/java/com/deque/html/axecore/selenium/Axe43xIntegrationTest.java

chore: improve finishRun error messages

---

src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java

chore: mark setLegacyMode as deprecated

---

CHANGELOG.md
package-lock.json
package.json
pom.xml

chore: merge master into develop

---

src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java

This functtion is needed to have devtools be able to test 43x

chore: add api to support devtools

---

src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java

docs: add @param for new function args

---

src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java

docs: javadoc fixes

---

pom.xml
src/main/java/com/deque/html/axecore/results/ToolOptions.java

chore: udpate ToolOptions for json

---

error-handling.md

docs: error handling

---

.circleci/config.yml
CHANGELOG.md
error-handling.md
package-lock.json
package.json
pom.xml
src/main/java/com/deque/html/axecore/axeargs/AxeRunContext.java
src/main/java/com/deque/html/axecore/extensions/WebDriverExtensions.java
src/main/java/com/deque/html/axecore/extensions/WebDriverInjectorExtensions.java
src/main/java/com/deque/html/axecore/providers/EmbeddedResourceAxeProvider.java
src/main/java/com/deque/html/axecore/providers/IAxeScriptProvider.java
src/main/java/com/deque/html/axecore/results/FrameContext.java
src/main/java/com/deque/html/axecore/results/Results.java
src/main/java/com/deque/html/axecore/results/TestEngine.java
src/main/java/com/deque/html/axecore/results/ToolOptions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java
src/test/java/com/deque/html/axecore/selenium/Axe43xIntegrationTest.java
src/test/java/com/deque/html/axecore/selenium/AxeExampleUnitTest.java
src/test/java/com/deque/html/axecore/selenium/AxeIntegrationUnitTest.java
src/test/java/com/deque/html/axecore/selenium/AxeRunContextUnitTest.java
src/test/resources/timeout.js

chore: release v4.3.0

---

src/main/java/com/deque/html/axecore/extensions/WebDriverExtensions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java

chore: add eh url to switchToWindow err

---

src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java

I am so mad this works.
Just to be clear, it is the json stuff that fixes it. Deleting the FIXME is just cleanup.

fix: finishRun stack overflow

---

package-lock.json
package.json
pom.xml
src/main/java/com/deque/html/axecore/extensions/WebDriverExtensions.java
src/main/java/com/deque/html/axecore/selenium/AxeBuilder.java

chore: release 4.3.1

---

package-lock.json
package.json
pom.xml

chore: update dependencies

---

CHANGELOG.md
package-lock.json
package.json
pom.xml
src/test/java/com/deque/html/axecore/selenium/AxeBuilderUnitTest.java

chore: release v4.4.0

---

.gitignore
.vscode/extensions.json

chore: add axe-linter as VSC recommendation

---

CODE_OF_CONDUCT.md

[rendered](https://github.com/dequelabs/axe-core-maven-html/pull/242/files?short_path=ffdbe3a#diff-ffdbe3a1e7ee93cacfc080b6c635ccf3a8f6b0f00f2fb884f78c6b5f9dac8fd2)

docs: add `CODE_OF_CONDUCT.md`

---

.circleci/config.yml

ci: ensure `utilities/pom.xml` is added to cache

---

playwright/package-lock.json
playwright/package.json
selenium/package-lock.json
selenium/package.json

feat: upgrade to use axe-core@4.5.0

---

playwright/package-lock.json
playwright/package.json
selenium/package-lock.json
selenium/package.json

fix: update to use axe-core 4.5.1

---

.github/workflows/create-release.yml

ci: change base branch to master

---

.github/workflows/create-release.yml

ci: use event not events

---

.github/workflows/semantic-pr-title.yml

ci: add semantic pr title GHA

---

.circleci/config.yml
.circleci/license-check.js

chore: license check

---

playwright/src/test/java/PlaywrightJavaTest.java
selenium/src/test/java/com/deque/html/axecore/selenium/Axe43xIntegrationTest.java

This PR adds missing test case for Selenium and Playwright. 
For reference, this was discussed on slack to ensure we can support both comma denoted lists and Array lists

test: add missing iframes test for completeness

---

selenium/README.md

docs(selenium): Fix code typo in README

---

.github/scripts/prerpare_release.sh
.github/workflows/auto-patch-release.yml
.github/workflows/tests.yml
package-lock.json
package.json
selenium/package-lock.json

Issue: https://github.com/dequelabs/axe-api-team/issues/333

ci: auto patch-release every 2 weeks

---

.github/workflows/auto-patch-release.yml

test: run patch job today at 12:30

---

.github/workflows/auto-patch-release.yml

ci: auto-patch-release from public repo

---

.circleci/config.yml

ci: fix browser-tools version

---

.github/workflows/auto-patch-release.yml

CI: Remove schedule from auto-patch-release.yml

---

.github/dependabot.yml
.github/workflows/create-release.yml
.github/workflows/update-axe-core.yml

This PR adds dependabot configuration for automatically updating dependencies for NPM, Maven and GitHub Actions.
Closes: https://github.com/dequelabs/axe-core-maven-html/issues/371

chore: add `dependabot.yml` configuration

---

.github/workflows/create-release-candidate.yml

Closes: https://github.com/dequelabs/axe-core-maven-html/issues/370

ci: add `create-release-candidate.yml` workflow

---

.circleci/config.yml

Closes: https://github.com/dequelabs/axe-core-maven-html/issues/381

ci: add release branch check to deploy.yml

---

.github/workflows/tests.yml
CHANGELOG.md
package-lock.json
package.json
playwright/package-lock.json
playwright/package.json
playwright/pom.xml
pom.xml
selenium/package-lock.json
selenium/package.json
selenium/pom.xml
utilities/pom.xml

Release v4.8.2

---

CHANGELOG.md
package.json
playwright/package-lock.json
playwright/package.json
playwright/pom.xml
pom.xml
selenium/package-lock.json
selenium/package.json
selenium/pom.xml
utilities/pom.xml

Release 4.10.1

---

.circleci/config.yml
playwright/pom.xml
pom.xml
selenium/package-lock.json
selenium/pom.xml
utilities/pom.xml

chore: update Sonatype URLs

---

playwright/pom.xml
pom.xml
selenium/pom.xml
utilities/pom.xml

ci: use correct Sonatype staging URL

---

playwright/src/main/java/com/deque/html/axecore/playwright/AxeBuilder.java

fix: remove duplicate "Please see"

---

playwright/src/main/java/com/deque/html/axecore/playwright/AxeBuilder.java

fix: remove superfluous space in exception message

---

.circleci/config.yml
.github/CODEOWNERS
.github/dependabot.yml
CHANGELOG.md
package-lock.json
package.json
playwright/README.md
playwright/package-lock.json
playwright/package.json
playwright/pom.xml
playwright/src/main/java/com/deque/html/axecore/playwright/AxeBuilder.java
pom.xml
selenium/README.md
selenium/package-lock.json
selenium/package.json
selenium/pom.xml
selenium/src/test/java/com/deque/html/axecore/selenium/Axe43xIntegrationTest.java
utilities/pom.xml

##
[4.10.2](https://github.com/dequelabs/axe-core-maven-html/compare/v4.10.1...v4.10.2) (2025-08-13)
* remove duplicate "Please see" ([#510](https://github.com/dequelabs/axe-core-maven-html/issues/510)) ([093cb06](https://github.com/dequelabs/axe-core-maven-html/commit/093cb06e58ff69a52c00d7c5c8c08e8f4ae6e490))
* remove superfluous space in exception message ([#518](https://github.com/dequelabs/axe-core-maven-html/issues/518)) ([7b0300c](https://github.com/dequelabs/axe-core-maven-html/commit/7b0300cc57dfa463a89559113726ef68a2ea4500))
* Update axe-core to v4.10.3 ([#501](https://github.com/dequelabs/axe-core-maven-html/issues/501)) ([b160777](https://github.com/dequelabs/axe-core-maven-html/commit/b1607774dd8f3b39465fc928a297c3d8ae974c0e))
No QA needed

chore: Release v4.10.2 (#528)
